(ns align_view.plots
  (:require [align_view.alignment-info :as al]
            [incanter core stats charts]))

(defn covered-bases
  "Takes the an entry from the map generated by align-info and outputs
  the covered bases in a sequence."  
  [entry]
  (range (:start entry) (+ 1 (:end entry))))

#_(defn hist 
  "Takes an entry from the map generated by align-info and outputs a
  histogram of the coverage."  
  [entry]
  (let [bases (covered-bases entry)]
    ))
